# Simple workflow for deploying Astro static site to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["master"]   # <— se il branch è main, cambia qui in "main"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      # Imposta automaticamente SITE/BASE_URL (supporta dominio custom via repo variable CUSTOM_DOMAIN)
      - name: Compute SITE and BASE_URL
        run: |
          if [ -n "${{ vars.CUSTOM_DOMAIN }}" ]; then
            echo "SITE=https://${{ vars.CUSTOM_DOMAIN }}" >> $GITHUB_ENV
            echo "BASE_URL=/" >> $GITHUB_ENV
          else
            OWNER="${{ github.repository_owner }}"
            REPO="${{ github.event.repository.name }}"
            echo "SITE=https://${OWNER}.github.io" >> $GITHUB_ENV
            if [ "$REPO" = "${OWNER}.github.io" ]; then
              echo "BASE_URL=/" >> $GITHUB_ENV
            else
              echo "BASE_URL=/${REPO}/" >> $GITHUB_ENV
            fi
          fi

      - name: Install dependencies
        run: npm ci

      - name: Build Astro
        env:
          SITE: ${{ env.SITE }}
          BASE_URL: ${{ env.BASE_URL }}
        run: npm run build

      # Preparazione Pages (consigliato da GitHub)
      - name: Setup Pages
        uses: actions/configure-pages@v5

      # Carica l'artefatto generato da Astro
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
